// Generated by https://quicktype.io

namespace Api.Authentication.Payload
{
	using System.Text.Json.Serialization;

	public partial class AuthPayload
	{
		[JsonPropertyName("username")]
		public string Username { get; set; }

		[JsonPropertyName("password")]
		public string Password { get; set; }

		[JsonPropertyName("grant_type")]
		public string GrantType { get; set; }

		[JsonPropertyName("client_id")]
		public string ClientId { get; set; }
	}
}
